import './globals.css'
import "swiper/css";
import "swiper/css/pagination";
import { Inter } from 'next/font/google'
import { HeroUIProvider } from "@heroui/react"
import AppHeader from '@/components/app.header'
import AppFooter from '@/components/app.footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <HeroUIProvider>
          <div className="min-h-screen flex flex-col">
            <AppHeader />
            <div className="flex-1 mt-12">
              {children}
            </div>
            <AppFooter />
          </div>
        </HeroUIProvider>
      </body>
    </html>
  )
}
